### ISSUE TITLE
App store approvals

### ISSUE THREAD

**Issue by reinink** [turbolinks/turbolinks-ios#104]
Hey there! 😊

I'm working on putting together my first Turbolinks iOS app. One thing that has me a little concerned is the app store approval process. Some folks [seem to suggest](https://stackoverflow.com/questions/7421002/app-rejected-from-apple-app-store-because-uiwebview-need-some-advice) that UIWebview style apps tend to not get approved.

I'm curious, from your experience have you had any issues with this, or have you heard of folks running into this when using Turbolinks?

Thanks!

**Comment by JonasNielsen** [comment]
No issues with our app. My impression is that as long as you build an app that follows the design guidelines Apple puts out and that the user experience is good, you should be OK.

**Comment by reinink** [comment]
@JonasNielsen Hey thanks! Do you mind telling me the name of your app? I'd love to see some in-production Turbolinks apps.

**Comment by zachwaugh** [comment]
We've shipped ~25 updates to Basecamp 3 for iOS over the last 1.5 years using Turbolinks, never had any rejections. There are a lot of other apps and frameworks that also use a hybrid approach without issue, I wouldn't worry about that at all.

**Comment by reinink** [comment]
Perfect, thanks @zachwaugh!
