### ISSUE TITLE
Swift 4 supports?

### ISSUE THREAD

**Issue by shieer** [turbolinks/turbolinks-ios#110]

**Comment by JimChen** [comment]
I created a PR #112. Maybe it's better to create a new branch for swift 4.0 like 'swift-3.0' instead of updating the master branch.

**Comment by zachwaugh** [comment]
I created a new branch `swift-4` with Swift 4 support and PR here - https://github.com/turbolinks/turbolinks-ios/pull/115 if anyone wants to test in their app. I haven't tested it yet in a real app.
