### ISSUE TITLE
Support for Swift 3.0

### ISSUE THREAD

**Issue by grandecomplex** [turbolinks/turbolinks-ios#117]
Hey team!

We are really excited to get started with Turbolinks iOS. However, the sample code is written in an older version of Swift. 

Xcode is telling me that version 9 does not support Swift 2!

![screen shot 2017-11-15 at 9 06 30 pm](https://user-images.githubusercontent.com/95575/32874805-5768e81e-ca49-11e7-81a8-8127132acc12.png)

**Comment by zachwaugh** [comment]
I just merged Swift 4.0 branch into master. It previously supported Swift 3, but maybe you had an older version? How are you integrating it there, are you pulling it in via CocoaPods/Carthage, or just opening the turbolinks-ios repo directly? Either way can you try pulling the latest master and doing a clean build, or using the `v3.0.0` tag?

**Comment by grandecomplex** [comment]
I think the error is generic. I saw it elsewhere when it meant 3.0.

That being said, with the latest commits it now works as expected! You guys rock. We are going to use this for the next gen version of our mobile apps.
