### ISSUE TITLE
delete method not support?

### ISSUE THREAD

**Issue by watsy0007** [turbolinks/turbolinks-ios#123]
eex(elixir render) code

```erb
<%= link "Delete", to: user_path(@conn, :delete, user), method: :delete, data: [turbolinks: true, remote: true], class: "btn btn-danger btn-xs" %>
```

html code
```html
<a class="btn btn-danger btn-xs" data-csrf="Ym==" data-method="delete" data-remote="true" data-to="/users/6" data-turbolinks="true" href="/users/6">Delete</a>
```

but when i click a tag. not work. it becomes post method!!!
<img width="1349" alt="default" src="https://user-images.githubusercontent.com/822237/33520634-f022a24e-d7f9-11e7-969a-25b94e79a514.png">

**Comment by pbmarcano** [comment]
Look at https://github.com/turbolinks/turbolinks-ios/issues/103 's last two answers and see if they help you. A little work is needed on the iOS side.

**Comment by zachwaugh** [comment]
Rails always sends `DELETE` as a `POST` to work in all browsers that may not support making `DELETE` requests directly, using a hidden `_method=DELETE` field:

>Because submitting forms with HTTP methods other than GET and POST isn't widely supported across browsers, all other HTTP methods are actually sent over POST with the intended method indicated in the _method parameter. Rails automatically detects and compensates for this.

http://guides.rubyonrails.org/working_with_javascript_in_rails.html#data-method

**Comment by watsy0007** [comment]
thanks @zachwaugh @pbmarcano
