### ISSUE TITLE
Need a way to handle deep link in email (ActionMailer)

### ISSUE THREAD

**Issue by mechanicles** [turbolinks/turbolinks-ios#129]
I tried to search this issue on other resources like StackOverflow but couldn't find any good one.

We do have an iOS app and Android app for our main web app. Our users get daily emails through Rails' ActionMailer. In emails, we do have some URLs which we want to get redirected to the particular mobile OS app if they are on mobile and have a mobile app version installed but currently, it gets redirected to the mobile's browser. Is there a way to handle this?

**Comment by zachwaugh** [comment]
Hi @mechanicles, on iOS the feature to handle that is called "universal links" - https://developer.apple.com/ios/universal-links/. You need to configure a special file on your web server and then implement the APIs in your app to handle the URL, from there you can hand it off and start a Turbolinks visit. That is outside the scope of the Turbolinks framework though.

**Comment by mechanicles** [comment]
@zachwaugh Thanks for sharing this. We will go through it.
