### ISSUE TITLE
Make WebView.callJavaScriptFunction() Public

### ISSUE THREAD

**Issue by joemasilotti** [turbolinks/turbolinks-ios#131]
I've started to reuse the helper function [`WebView.callJavaScriptFunction()`](https://github.com/turbolinks/turbolinks-ios/blob/ac09406eefedf37fc96ecab56bb05879289e0858/Turbolinks/WebView.swift#L75) in a few of my Turbolinks projects. The encoding and extra level of error handling have proved extremely useful. I've usually just copied and pasted it.

Instead, would a PR be accepted if this function was made public? Or extracted out to its own helper that works with `WKWebView` directly? Or should this function (and its callees) not be used outside of the framework?

**Comment by joemasilotti** [comment]
One month check-in! Any thoughts on this?

**Comment by zachwaugh** [comment]
I think we should keep this private, in case we need to change how that works internally, we don't want to worry about breaking any clients.

**Comment by digerata** [comment]
@joemasilotti I'm wondering the best way to expose this function. Just getting familiar with the framework. It seems like we need to subclass `WebView` and somehow pass that to `Session`? Do you have a public branch you could share?
