### ISSUE TITLE
Replace ActivityIndicatorView with a custom view

### ISSUE THREAD

**Issue by lazaronixon** [turbolinks/turbolinks-ios#133]
have any way to customize activityIndicator like baseCamp does ?

**Comment by zachwaugh** [comment]
Basecamp uses the built-in `UIActivityIndicatorView` provided by Turbolinks. You could create a `VisitableView` subclass though and override `showActivityIndicator()` and `hideActivityIndicator()` to do whatever you want.

**Comment by lazaronixon** [comment]
Ok I did it. But how can I set visitableView on VisitableViewController since it is a let variable and I cant override it too since it is a lazy var.
