### ISSUE TITLE
Compiler warning in Xcode 9.3 - weak should not be applied to a property declaration .. 

### ISSUE THREAD

**Issue by wrtsprt** [turbolinks/turbolinks-ios#134]
* Xcode 9.3
* Turbolinks-iOS commit: ac09406eefedf37fc96ecab56bb05879289e0858

/Pods/Turbolinks/Turbolinks/Visitable.swift:12:5: 'weak' should not be applied to a property declaration in a protocol and will be disallowed in future versions

**Comment by joemasilotti** [comment]
Fixed in proposed PR #135

**Comment by zachwaugh** [comment]
Merged the fix
