### ISSUE TITLE
Startup Performance

### ISSUE THREAD

**Issue by jeffmcfadden** [turbolinks/turbolinks-ios#141]
What are the best practices for optimizing startup performance? We have an app with several tabs, and first-launch experience (and app resume) pretty much sucks. We've optimized the heck out of our site infrastructure, but even a 100ms response time feels like forever once you add DNS resolution, latency, and related resource (css/js) fetching.

We have some ideas about how we can optimize the experience, but I thought we should ask if anyone else has a clever solution to this that they've already tried, before we go diving deep.

**Comment by zachwaugh** [comment]
I'm sorry to say I don't really have good advice here. If all your tabs are web views loading remote pages, I don't think there is too much you can do to really make it fast. In Basecamp, all the initial view controllers for our main 4 tabs are 100% native for this exact reason.
