### ISSUE TITLE
How to "nstall Turbolinks manually by building Turbolinks.framework and linking it to your project."

### ISSUE THREAD

**Issue by grapevinegizmos** [turbolinks/turbolinks-ios#152]
I realize this is a newbie question, but this quickstart is for newbies, can you explain how to  "Install Turbolinks manually by building Turbolinks.framework and linking it to your project"?    Its the only thing that isn't explicitly documented, and and interweb search isn't of obvious help.

I am rails person, and don't know that much about Ios but excited to try Turbolinks for cross platform work.   I am used to adding gems in rails but don't have experience with "building things" for ios and suspect that is true for others. Thanks.

**Comment by zachwaugh** [comment]
Unless you have some reason to build manually, I would recommend using [Carthage](https://github.com/carthage/carthage). It's similar to Bundler and will take care of fetching, building, and updating Turbolinks. The only thing you'll have to do is link it to your app which is documented here https://github.com/carthage/carthage#if-youre-building-for-ios-tvos-or-watchos.

To do it completely manually is more advanced, but roughly you'd clone this repo, open the turbolinks-ios.xcworkspace, build the framework from Product > Archive, take the built Turbolinks.framework and link it to your app, ensuring it's correctly copied into your app bundle. Here's some more info about embedding the framework - https://developer.apple.com/library/archive/technotes/tn2435/_index.html
