### ISSUE TITLE
JavaScript error: Cross origine request for webcal://

### ISSUE THREAD

**Issue by tony42** [turbolinks/turbolinks-ios#166]
We are trying to load a webcal:// URL from the same domain we run the whole app from. It appears that Turbolinks are trying to load this URL as a "local" page but iOS treats it as an external site.

I see this error in XCode console:

`2020-01-31 12:28:58.902232+0100 HlidackyMobileApp[7011:2628385] Error evaluating JavaScript function 'webView.changeHistoryForVisitWithIdentifier': SecurityError: Blocked attempt to use history.pushState() to change session history URL from https://www.hlidacky.cz/rezervace to webcal://www.hlidacky.cz/export_calendars/XiT5RF3ZPMyPFbXiwJpAK79N.ics. Protocols, domains, ports, usernames, and passwords must match.`

And Turbolinks will call `session(_ session: Session, didFailRequestForVisitable visitable: Visitable, withError error: NSError)`

If I try to load a webcal:// URL form a different domain, everything works as expected.

My best guess is that Turbolinks JavaScript compares the domain part of the URL and if it matches, it loads the URL as "internal" which causes the error. If that is correct, one needs to extend to code to compare the domain and the URL scheme.

**Comment by petrsigut** [comment]
So I wonder how you do that in Basecamp iOS app?:) Is there some javascript workaround to open the calendar?

![IMG_0264](https://user-images.githubusercontent.com/87228/73554128-71297600-444b-11ea-8ac1-97ada4fe7e83.PNG)
![IMG_0262](https://user-images.githubusercontent.com/87228/73554156-7b4b7480-444b-11ea-884c-296358fff385.PNG)

Thank you very much for reply!

**Comment by petrsigut** [comment]
In the Basecamp iOS app, it works flawlessly, but I do not know if there are some more js to handle the calendar opening. Any point in the right direction appreciated! 

![IMG_0264](https://user-images.githubusercontent.com/87228/73554460-088ec900-444c-11ea-9edf-ccc87196b329.PNG)

**Comment by zachwaugh** [comment]
For links like that, Turbolinks will ignore them, and they will hit the `WKNavigationDelegate`. In Basecamp, we process any URLs there and send them through our router which determines where they need to open. For something like that, we just open them with the system.

I'm not sure where that error is coming from since I can't reproduce in Basecamp. Possibly, you're trying to send that link back through Turbolinks?

**Comment by tony42** [comment]
@zachwaugh `WKNavigationDelegate` was the hint I needed :-) Turbolinks.Session is actually the delegate and it correctly calls `SessionDelegate.session(self, openExternalURL: URL)`

The issue was on our side in the external URL handling.

Closing this issue but thanks for the assistance.
