### ISSUE TITLE
Allow webview to display under the status bar/ notch

### ISSUE THREAD

**Issue by gearoidoceallaigh** [turbolinks/turbolinks-ios#168]
Whilst the webview in my Turbolinks project allows content to scroll "underneath" the notch/status bar, it seems as though it's impossible to get the webview to start underneath it by default.

It seems like the common solution to achieve this is:

`webview.scrollview.contentInsetAdjustmentBehavior = .never`

However, this has brought me no joy.

I've tried removing/adding constraints around containers but no luck.

Does anyone happen to know if this is possible using the (superb) turbolinks-ios library?

**Comment by zachwaugh** [comment]
Do you have a screenshot of what you mean? Besides the native side of it, you also need to have the HTML configured correctly - https://webkit.org/blog/7929/designing-websites-for-iphone-x/, specifically the viewport setting:

```html
<meta name='viewport' content='initial-scale=1, viewport-fit=cover'>
```

**Comment by gearoidoceallaigh** [comment]
Hi @zachwaugh 

I forgot to specify I've already added the `viewport-fit=cover` to `viewport` meta tag.

Below is a primitive example of what I'm trying to accomplish.

![image](https://user-images.githubusercontent.com/287567/78803011-655fb000-79b6-11ea-9e83-5b88d7fa252f.png)

I would expect the above to display "howdy" underneath the status bar.

Obviously this isn't my intended use. I'm trying to get the page background image to display underneath the status bar/notch. Unfortunately, it displays underneath both of these, just like the howdy text.

**Comment by gearoidoceallaigh** [comment]
I should also mention that the view controller in this instance is a child of a navigation controller whose navigation bar is (temporarily) hidden.
