### ISSUE TITLE
iOS simulator isn't starting

### ISSUE THREAD

**Issue by xerervw** [turbolinks/turbolinks-ios#169]
Hi, I am new to xcode and trying to run the demo app on an iOS simulator. 
Can't get the simulator to start.. Also tried manually opening the simulator, but it doesn't have the demo app installed on it.

Running it on localhost does work. And opening the app in browser also..

Could someone help me with this?
Thanks

**Comment by bilal62** [comment]
Under Product -> Scheme -> Edit Scheme, check these settings once.
![image](https://user-images.githubusercontent.com/4471320/93705783-065da580-fad5-11ea-9543-a5620db8d1ad.png)
