### ISSUE TITLE
Swift Package Manager Support

### ISSUE THREAD

**Issue by bazscott** [turbolinks/turbolinks-ios#172]
Now that Xcode 12 is almost out and Swift Package Manager is useful on most projects, it would be great if Turbolinks supported SPM.

**Comment by zachwaugh** [comment]
Thanks @bazscott! I'm going to close because this framework is being replaced by [Turbo iOS](https://github.com/hotwired/turbo-ios) which supports SPM. More details here: https://github.com/turbolinks/turbolinks-ios/pull/178
