### ISSUE TITLE
`openURL` was deprecated in iOS 10.0

### ISSUE THREAD

**Issue by joemasilotti** [turbolinks/turbolinks-ios#176]
These warnings only occur if the deployment target is set to iOS 10.0 or above.

> Turbolinks/Turbolinks/Session.swift:19:30: 'openURL' was deprecated in iOS 10.0
> Turbolinks/Turbolinks/Visit.swift:186:38: 'openURL' was deprecated in iOS 10.0

There recommended approach is to replace `openURL` with `open(_: options: completionHandler:)`.

If I were to submit a PR, would it be reviewed? I understand this project is in a bit of a weird state with Turbo around the corner.

**Comment by zachwaugh** [comment]
Fixed in [Turbo iOS](https://github.com/hotwired/turbo-ios). More info on the new framework here - https://github.com/turbolinks/turbolinks-ios/pull/178
