### ISSUE TITLE
[Question] Is it possible to fire Turbolinks JavaScript events on a ColdBootVisit?

### ISSUE THREAD

**Issue by joemasilotti** [turbolinks/turbolinks-ios#19]
The first call to `visit()` on the `Session` creates a `ColdBootVisit`. In turn, this makes a standard network request via `loadRequest()` on `WKWebView`, **without Turbolinks**.

Because of this the `turbolinks:request-start` event is not fired. This makes it impossible to modify the XHR for the first request of any Turbolinks session. (I am trying to set [custom HTTP headers](https://github.com/turbolinks/turbolinks#setting-custom-http-headers) for each XHR that is made through Turbolinks.)

Is there a workaround to achieve what I am trying to accomplish?

**Comment by joemasilotti** [comment]
#20 demonstrates how opening up the HTTP headers on the initial request could be done.

**Comment by sstephenson** [comment]
The initial page load isn’t an XHR, and since by definition the page hasn’t loaded, there’s no active JavaScript context, which means there’s no way to fire the request-start event.
