### ISSUE TITLE
visitableDidRender is not getting called

### ISSUE THREAD

**Issue by phil-monroe** [turbolinks/turbolinks-ios#22]
This is probably a silly question since I am a just starting out on iOS development with Swift, but I cannot seem to define a `visitableDidRender` and actually have it ran. I am playing around with the demo application and added the following to `DemoViewController`, but `visitableDidRender` never seems to be called...

``` swift
class DemoViewController: Turbolinks.VisitableViewController {
    // Snip...
    func visitableDidRender() {
        print("running visitableDidRender() in \(self)")
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        print("running viewDidLoad() in \(self)")
    }
}
```

It looks like it should be called from `Session`. I modified the `Session: VisitDelegate` extension with the following and it makes me feel like I am putting `visitableDidRender` in the right place, on `DemoViewController`:

``` swift
extension Session: VisitDelegate {
    // Snip...
    func visitDidInitializeWebView(visit: Visit) {
        initialized = true
        delegate?.sessionDidLoadWebView(self)
        print("calling visitableDidRender() from visitDidInitializeWebView() on \(visit.visitable)")
        visit.visitable.visitableDidRender()
    }

    func visitDidRender(visit: Visit) {
        visit.visitable.hideVisitableScreenshot()
        visit.visitable.hideVisitableActivityIndicator()
        print("calling visitableDidRender() from visitDidRender() on \(visit.visitable)")
        visit.visitable.visitableDidRender()
    }
}
```

This gives the following output when running the app:
```
running viewDidLoad() in <TurbolinksDemo.DemoViewController: 0x7ff9b941f540>
calling visitableDidRender() from visitDidInitializeWebView() on <TurbolinksDemo.DemoViewController: 0x7ff9b941f540>
calling visitableDidRender() from visitDidRender() on <TurbolinksDemo.DemoViewController: 0x7ff9b941f540>
```

I would expect to also see the output `running visitableDidRender() in <TurbolinksDemo.DemoViewController: 0x7ff9b941f540>`, but it seems that `visitableDidRender` is never actually ran on `DemoViewController`

I feel that I must be missing something either about how the lifecycle of a `Turbolinks.VisitableViewController` or Swift in general. Any thoughts? I'd be happy to contribute some extra documentation if I am misunderstanding the [README](https://github.com/turbolinks/turbolinks-ios#setting-visitable-titles)

You can look at my fork to see the full context of what I have added: https://github.com/phil-monroe/turbolinks-ios

**Comment by sstephenson** [comment]
Hi Phil. Thanks for opening this issue. You’re not missing anything! It’s our mistake.

Apparently, if a Swift class doesn’t explicitly implement a method provided by a default protocol implementation, subclasses can’t override the default behavior. ([More information here](https://medium.com/ios-os-x-development/swift-protocol-extension-method-dispatch-6a6bf270ba94#.ryw3xdz9u).)

So if you’d implemented the Visitable protocol yourself, there’d be no issue. But if you subclassed VisitableViewController, your definition of `visitableDidRender` would never be called.

I’ve just released version 1.0.2 of the framework which includes a fix. Note that you’ll need to use the `override` keyword when defining your VisitableViewController subclass’s `visitableDidRender` method.
