### ISSUE TITLE
Restore scroll position on session reload

### ISSUE THREAD

**Issue by Bramjetten** [turbolinks/turbolinks-ios#24]
After reloading a Turbolinks session, the scroll position is reset to the top. Is there a way to maintain this scroll position without manually setting it on turbolinks:load?

**Comment by phil-monroe** [comment]
@Bramjetten I had the same issue when I first migrated our webapp that had the css: `overflow: scroll`. Turbolinks will not reset any scrollable div's but does reset the page position quite nicely! Hope that helps.

**Comment by zachwaugh** [comment]
@Bramjetten unfortunately isn't supported by Turbolinks currently. When the session reloads, all the state related to previous visits (including the scroll position) is stored in JavaScript, and that state is cleared out on reload. As a workaround for now you would have to store it natively and restore it manually.
