### ISSUE TITLE
Would it be interesting to separate turbolinks 5-enabled web app/server requirement from the rest of it?

### ISSUE THREAD

**Issue by exalted** [turbolinks/turbolinks-ios#27]
Given that I barely scratched the surface on this; I would like to know your comments about the work required to separate the *native navigation and a single shared web view* feature from the *Turbolinks 5-enabled web app* feature.

Reasoning: I like the idea of laying out my views using web views, but then I don’t always have a fully functional web[site/app]; instead sometimes all you need/have is a (JSON) API that returns some data.

This probably would defeat the purpose of turbolinks, yet you *might* avoid reloading JavaScript and CSS and definitely save memory by sharing one WKWebView. So the *native navigation and a single shared web view* feature is seriously 🆒 .

Not sure where I am headed this at this point, but I would appreciate to hear your thoughts and if could I maybe help getting there if there is enough interest to it.

:beers:

**Comment by zachwaugh** [comment]
That is an interesting idea! But since this framework is tightly coupled to a web server using Turbolinks, I don't think it would make sense to tackle that as part of this project though.

**Comment by exalted** [comment]
@zachwaugh thanks and that sounds like saying rails was initially tied to turbolinks, so it wouldn't make sense to separate it from rails or something like that.

Regardless, I really don't have strong opinions about this as I have no actual use case. I am glad we had a chance to think about it for a brief moment. 

Cheers!
