### ISSUE TITLE
Demo app fails to show pages if main URL is changed to common websites

### ISSUE THREAD

**Issue by timriley** [turbolinks/turbolinks-ios#28]
Hi there Turbolinkers – I really love the look of this framework and I'm hoping to adopt it for an app we're building. However, I'm having some trouble getting a basic app started, because our subclasses of VisitableViewController (even with zero customisations yet) are never showing the webpages we're trying to load. They do end up replacing the navigation controller's title with the web page's title, but the loading spinner never goes away and the webview never appears.

I was wondering if it was something I was doing wrong with the basic setup of turbolinks-ios in my own project, but I discovered that if you take the TurbolinksDemo app and change `ApplicationController`'s `URL` to something like `"http://google.com/"` or `"https://basecamp.com/"`, then the very same thing happens in the demo app too. You end up just looking at this:

<img width="578" alt="screen shot 2016-04-11 at 11 30 25 pm" src="https://cloud.githubusercontent.com/assets/3134/14428697/7383fa02-003d-11e6-90bd-09606ee976b3.png">

I'm still trying to dig around the library to see why this might be the case, but I thought I might file an issue in case it's an obvious fix to any of you as the authors. Thanks for your help!

**Comment by timriley** [comment]
Sorry, I accidentally submitted too early. I've just updated the issue description with a sample screenshot and a final note. Thanks!

**Comment by timriley** [comment]
Oh, I think I might've found the reason – I was thinking that this would load arbitrary web pages as a starting point, but is it actually the case that the VisitableView needs Turbolinks' JS code present somehow so it can send some sort of initial page load event?

**Comment by sstephenson** [comment]
I’m afraid there’s no bug here. Turbolinks for iOS provides a native adapter for Turbolinks 5-enabled web apps. You have to point the web view to a page that includes turbolinks.js.

Neither the Google home page nor the Basecamp marketing site use Turbolinks. The [bundled demo app does use Turbolinks](https://github.com/turbolinks/turbolinks-ios/blob/master/TurbolinksDemo/server/lib/turbolinks_demo/views/layout.erb#L7), as does the Basecamp 3 web app (which you see after logging in at basecamp.com).

We’ve tried to explain this up front. Here’s the second sentence of the readme:
> Turbolinks for iOS provides the tooling to wrap your Turbolinks 5-enabled web app in a native iOS shell.

But perhaps that’s not clear enough. Any suggestions on what would make this more obvious?

**Comment by timriley** [comment]
Hi @sstephenson, thanks for taking the time to reply to me. I led myself down a wrong path before filing this issue, which I now fully understand (the Rails app I was testing against had turbolinks.js only available in some of the pages).

I think your README is pretty clear. If anything, what would've helped in my situation would be a warning printed to Xcode's debug area if the `VisitableView`'s `webView` detects that a page has fully loaded without receiving any of the required Turbolinks events. However, I do understand this wouldn't be a priority for you :)

**Comment by sstephenson** [comment]
> If anything, what would've helped in my situation would be a warning printed to Xcode's debug area if the VisitableView's webView detects that a page has fully loaded without receiving any of the required Turbolinks events.

That’s a great suggestion. Would you be interested in working on this?

**Comment by timriley** [comment]
I'd certainly be happy to give it a try! Once I get our app up and running, I'll familiarise myself a little more with the turbolinks-ios code and look to put this in place.
