### ISSUE TITLE
Question: Offline capabilities

### ISSUE THREAD

**Issue by nik736** [turbolinks/turbolinks-ios#29]
Hi,

thanks for the great work!

I will develop an app for a new project and the first page/view will fetch an image from an API and display it. It would be important that this image will be shown even if there is no internet connection (like loading it once when there is a connection available, and it will be displayed even when there is no internet connection every time afterwards). Would that be somehow possible using turbolinks?

Thanks!!

**Comment by zachwaugh** [comment]
I'm exactly sure what you're trying to do, but it sounds like something out of scope for Turbolinks. I would probably handle that with native code.
