### ISSUE TITLE
Can't trigger UJS link from iOS

### ISSUE THREAD

**Issue by glennfu** [turbolinks/turbolinks-ios#31]
I have a button in my iOS app that calls a javascript function. That javascript function calls `$("#sign-out").click()`. That element looks like `<a id="sign-out" href="/users/logout" data-method="delete" rel="nofollow">Sign out</a>`

Calling the `.click()` from Firebug works fine, but in my turbolinks-ios app, nothing happens. I can debug to ensure that the element I'm calling it on exists, but the link doesn't get followed.

Similarly, for a regular `<a id="sign-in" href="/users/signin">Sign in</a>` link, calling `$("#sign-in").click()` has no effect, yet `$("sign-in").get(0).click()` DOES work, but of course that doesn't help in the first case because that would skip the UJS.

Any ideas of what I'm missing or what I need to do here?

**Comment by jun1st** [comment]
for non GET methods,  `data-remote="true"` is required, try add this to your sign out anchor

**Comment by glennfu** [comment]
Good to know! I've added this and reworked the redirects and now it works properly. Thank you!
