### ISSUE TITLE
Removal of field navigation bar over keybaord

### ISSUE THREAD

**Issue by paulcsmith** [turbolinks/turbolinks-ios#32]
Is it possible to remove the field navigation bar (the arrows and the "done") when you focus a field in a webview? If not, I think that would be a lovely feature :)

Maybe a way to tie closing the keyboard to a native element so the bar is no longer me essay?

![image](https://cloud.githubusercontent.com/assets/22394/14576529/e961dcec-0337-11e6-9b8f-841130c96ccd.png)

**Comment by zachwaugh** [comment]
Unfortunately, that's controlled by `WKWebView`, and it doesn't provide any public APIs to change or customize it. Hopefully in a future version of iOS, `WKWebView` will let us control that.

**Comment by paulcsmith** [comment]
Bummer! Maybe in iOS 10 :)
