### ISSUE TITLE
Hiding the activity indicator

### ISSUE THREAD

**Issue by glennfu** [turbolinks/turbolinks-ios#33]
Here's what's currently in Session.swift:

```
func visitDidRender(visit: Visit) {
        visit.visitable.hideVisitableScreenshot()
        visit.visitable.hideVisitableActivityIndicator()
        visit.visitable.visitableDidRender()
    }
```

With this, the page is displayed before visitableDidRender() gets called. As I understand it, this is the only place for a bridge to hook into changing any native components on the screen for a page. I have a cast in my app where in response to something on the page, I construct a new native element near the top of the page. In doing so, the web view has to shift down. This causes a quick bounce in the visuals which is no good. Swapping the order of `visitableDidRender` and `hideVisitableActivityIndicator` fixes this. Now I get to control exactly when I'm ready for the page to be displayed.

Is this a good change? Do you see any problems with it? From my perspective, you can basically get the same original behavior if you really want it just by making sure your `visitableDidRender` is asynchronous.

**Comment by zachwaugh** [comment]
@glennfu hiding the screenshot and activity indicator is part of rendering, so I don't think we want to change the order those methods are called. Your best bet would be to create a custom `Visitable` that doesn't use the default `VisitableView`, and then you'll have full control over the display.

We could also add a `visitableWillRender()` hook that is called before everything else, if that would work better.
