### ISSUE TITLE
Design advice: structuring an app to make modally presented view controllers work with the session

### ISSUE THREAD

**Issue by timriley** [turbolinks/turbolinks-ios#36]
We’re getting started with a serious Turbolinks-iOS app. In our early work, it’s looking really great (thank you for sharing your code! 😄), but we’ve come across a hitch:

Our app has an initial `UINavigationController` subclass, very much like your demo app.

By default, it displays a “dashboard” screen with links to the various sections of our app.

Tapping those links will push in different `UIViewController` subclasses, which are custom to each section.

_(The per-URL view controllers are built by a very simple “Router” object, whose job it is to take a URL and return an appropriate view controller instance for that URL)._

In one of the app’s sections (“Tasks”), we have a “+” button in the navigation bar to create a new task. Since this will show a form, we take a common iOS approach: present a new modal `UINavigationController` with a `TaskComposerViewController` (a `Turbolinks.VisitableViewController` subclass) as its root VC:

```swift
func didTapAddTask(sender: UIBarButtonItem) {
        let composerVC = TaskComposerViewController()
        let navVC = UINavigationController(rootViewController: composerVC)
        presentViewController(navVC, animated: true, completion: nil)
}
```

This TaskComposer view controller sets its own visitableURL in its initializer. However, it can never end up displaying its web content, because it is now one step removed from the app’s initial `UINavigationController`, which is the delegate for the Turbolinks `Session` object. This means the task composer view controller (or its `navVC`) has no way to get a `session.visit(visitable)` to happen.

Do you have any suggestions for how to make a structure like this workable with turbolinks-ios? In essence, we need:

1. To use custom view controllers to show the various pages in our app, so they can add extra items to the navigation bar (this one seems easy enough to do).
2. To allow view controllers created and displayed _outside_ of the original navigation controller’s stack to still somehow work with the Turbolinks session (this is where I’m a bit stuck).

I’ve been mulling over some potential arrangements to fix this:

* Manually pass the session from VC to VC as they are created, reassigning its delegate as we go (but this feels like it might need a lot of code to be repeated across multiple VCs)
* Make a “router” (or something similar) hold the Turbolinks session (and the other webkit things it needs), and have that router maintain a stack of pushed/presented VCs, which it can then set/unset as the session’s delegate when each VC is added or removed to/from the stack.

Both of these seem like they could get pretty finicky, which is why I thought I might run this query past you here first. In regular iOS app development, the “modally present a new navigation controller” pattern is pretty common, so I thought it might’ve been something you’ve already tackled in the Basecamp app or any other turbolinks-ios experiments of your own.

Is there any chance you could offer some pointers about what a good structure might be for using turoblinks-ios with the arrangement I described above?

Thank you for your help! 🙏 And if you’d like me to take a query like this elsewhere, I’d be happy to do that.

**Comment by zachwaugh** [comment]
In Basecamp 3, we have a `TurbolinksController` that owns the Turbolinks `Session` and is the `SessionDelegate`. This object hands off visit requests to our router and navigator that take care of figuring out what view controller to load and how to present it, respectively. The navigator has a delegate method that is called before a view controller is presented, and the `TurbolinksController` calls `session.visit(visitable)` in that method. We don't set/unset the session delegate or need to pass the session around with this setup.

Hope that helps, but happy to give more details if you need.

**Comment by timriley** [comment]
@zachwaugh Thanks very much for your reply! Your separation of responsibilities makes a lot of sense, but I'm still having trouble making the arrangement work in practice. I've written up some more background and included some of attempt in code here: https://gist.github.com/timriley/5e2a17c3b8c21e0ef02c21919bd9a53d

If you wouldn't mind taking a look and letting me know what you think, I'd really appreciate it! Thank you!

**Comment by zachwaugh** [comment]
Left some comments on the gist, going to close this, but feel free to ping me with more questions.

**Comment by timriley** [comment]
@zachwaugh Just replying here, since I'm not sure whether @-pings on gists actually work. It's now Monday night here in Australia and I've spent the day sorting out a structure that works more along the lines of your most recent comments – and it works! Thank you for your patience in explaining some of these approaches to me 😄 

I have to push forward and get some more parts of this particular app built out, but before too long I'll circle back and put together an example app to see what you think.

Thanks again 🎉 🎉

**Comment by cdmwebs** [comment]
@timriley @zachwaugh this post & the gist have been super helpful. Thank you! @timriley: is there anyway you can share more of what you learned with respect to router/navigator/turbolinks controller?

**Comment by pbmarcano** [comment]
@timriley do you have any gists of this pattern finished? Or maybe the initial example broken into this kind of pattern?

I am trying to refactor an app since my turbolinks controller became this god class.
