### ISSUE TITLE
Setting custom headers

### ISSUE THREAD

**Issue by jvanbaarsen** [turbolinks/turbolinks-ios#39]
I was wondering if it is possible to set a custom header value? (For example `X-DeviceToken`).

**Comment by DarkSwoop** [comment]
```javascript
document.addEventListener("turbolinks:request-start", function(event) {
  var xhr = event.data.xhr
  xhr.setRequestHeader("X-DeviceToken", 'your-token');
});
```

**Comment by jvanbaarsen** [comment]
@DarkSwoop Thanks! But that is inside the web-app right? I mean from swift towards the web app

**Comment by wassimk** [comment]
Hey @DarkSwoop and @jvanbaarsen --- have you guys figured this out? After a user logs into the application, I need to send the users API key back to the Swift app so any native views can query the applications API for data. I was thinking about doing it by setting a custom header but how can the Swift app access the header?

**Comment by joemasilotti** [comment]
@wassimk you can send the token by adding a script handler.

Script handlers are essentially bridged between JavaScript and Swift/Objective-C code. You call them from JavaScript and your native code receives the function call and parameters encoded as strings, numbers, arrays, and dictionaries.

You add script handlers to the `WKUserContentController` which lives on the `WKWebViewConfiguration`. After you add scripts to the controller attach said controller to the configuration. Then you can inject the configuration into the Turbolinks `Session`.

For example:

```swift
import WebKit

let AuthTokenMessage = "authToken"

class ScriptMessageHandler: NSObject, WKScriptMessageHandler {
    func userContentController(userContentController: WKUserContentController, didReceiveScriptMessage message: WKScriptMessage) {
        if let authToken = message.body as? String where message.name == AuthTokenMessage {
            // use auth token
        }
    }
}

let configuration = WKWebViewConfiguration()
configuration.userContentController.addScriptMessageHandler(ScriptMessageHandler(), name: AuthTokenMessage)

let turbolinkSession = Session(webViewConfiguration: webViewConfiguration)
```

**Comment by zachwaugh** [comment]
The way we chose to handle this in Basecamp 3 is by doing authentication completely outside of Turbolinks. When the user authenticates successfully, we get back an OAuth token which we persist in the Keychain and use for all native API requests with `NSURLSession`.

When we load a Turbolinks web view the first time, we authorize the request with our OAuth token, and the server sets session cookies in the web view. Those cookies are automatically persisted by WebKit, which means it only needs to happen on the first login. This method has worked well for us and doesn't require trying to set a header for every request or moving auth tokens between native and web. Let me know if anyone wants more details about that method. We're also going to write up something about this and add it to the docs.

**Comment by rayfix** [comment]
@zachwaugh Just wondering how do you authorize the request with the OAuth token for the first time. The sample app doesn't do this, right?

**Comment by wassimk** [comment]
Hi @zachwaugh --- thanks for the information. Yes, I would like more information on this. I'm looking forward to the documentation.

In your write-up could you comment on the method @joemasilotti is talking about too? 

With another method being once user logs in with a web view the page redirected to post-login sends a JavaScript message with the API token.

**Comment by dgilperez** [comment]
Very interesting @zachwaugh any extra info?

**Comment by p8** [comment]
@zachwaugh is probably using [OpenID Connect](https://developer.pingidentity.com/en/resources/napps-native-app-sso.html#how_it_works), a standard build on top of OAuth2.
To use OpenID Connect you could use the [AppAuth](https://github.com/openid/AppAuth-iOS) library ([more info](https://www.pingidentity.com/en/blog/2016/03/10/using_appauth_to_enable_your_apps_with_mobile_sso.html))

**Comment by oarod** [comment]
@zachwaugh Was this ever written up anywhere?

**Comment by hhgz9527** [comment]
=w=, where docs?  @zachwaugh

**Comment by zachwaugh** [comment]
This is long overdue, but I wrote up a bit more about how we handle auth in BC3 - https://github.com/turbolinks/turbolinks-ios/blob/master/Docs/Authentication.md.
