### ISSUE TITLE
Page loading issue

### ISSUE THREAD

**Issue by kuba108** [turbolinks/turbolinks-ios#40]
Hi, I do not know what I am doing wrong, but page won't load in my turbolinks test app. I follow steps in this tutorial (https://github.com/turbolinks/turbolinks-ios/blob/master/QuickStartGuide.md) and when I am in step 3 and I run app, title will show but page won't load (see printscreen).
I run the plutil command. What I am doing wrong? Thanks for any advice.

![image](https://cloud.githubusercontent.com/assets/5421250/15656527/a3e7eae6-26a8-11e6-864f-f46797d1c670.png)

**Comment by zachwaugh** [comment]
Are you running the [local demo server](https://github.com/turbolinks/turbolinks-ios/blob/master/README.md#running-the-demo) or did you change the URL? It looks like you may be trying to hit basecamp.com, which doesn't use Turbolinks, so it wouldn't trigger the event to tell the framework the page has loaded. You'll need to make sure you hit a site that uses Turbolinks 5.

**Comment by kuba108** [comment]
@zachwaugh Thanks for reaction. You are right that in attached image I am trying Basecamp with URL: https://basecamp.com. However, I also tried localhost app where I have turbolinks and this web app http://mlynkamenice.cz which also runs turbolinks and result is same: title changes but web page won't load.

**Comment by sstephenson** [comment]
Hi @kuba108,

I don’t know about your local app, but mlynkamenice.cz is not running Turbolinks 5. Your site must be using Turbolinks 5 for the native adapters to work.

Hope this helps!

**Comment by kuba108** [comment]
Hi @sstephenson,

sorry, I have overlooked that it must be version 5. So thats it. I knew I will embarrass myself :)
Thanks for explanation.

BTW: TB5 is great and your presentation on RailsConf is wonderful.
