### ISSUE TITLE
Unable to load page

### ISSUE THREAD

**Issue by bryanvero** [turbolinks/turbolinks-ios#42]
I am trying to add Turbolinks-ios to an existing ios project. I have created a new view controller that is embedded in a navigation controller.  I have added the code below and it does load the web display and begin spinning, but it does not load the contents of the webpage. I have confirmed that going to Safari in the simulator does load the page without issue.

```
import UIKit
import Turbolinks

class SignInView: UIViewController {
    var window: UIWindow?
    var session = Session()

    override func viewDidAppear(animated: Bool) {
        session.delegate = self
        visit(NSURL(string: "http://192.168.1.8:3000")!)
    }

    func visit(URL: NSURL) {
        let visitableViewController = VisitableViewController(URL: URL)
        navigationController!.pushViewController(visitableViewController, animated: true)
        session.visit(visitableViewController)
    }
}

extension SignInView: SessionDelegate {
    func session(session: Session, didProposeVisitToURL URL: NSURL, withAction action: Action) {
        visit(URL)
    }

    func session(session: Session, didFailRequestForVisitable visitable: Visitable, withError error: NSError) {
        let alert = UIAlertController(title: "Error", message: error.localizedDescription, preferredStyle: .Alert)
        alert.addAction(UIAlertAction(title: "OK", style: .Default, handler: nil))
        navigationController!.presentViewController(alert, animated: true, completion: nil)
    }
}
```

The page being loaded is just a simple page with a few assets. I also tried to test this against https://google.com and it just spins the same way.

**Comment by joemasilotti** [comment]
The website needs to be running Turbolinks v5 installed for the iOS framework to work. Google does *not* have the JavaScript library.

**Comment by ericgross** [comment]
Gotcha. I figured it would load the first page and then be broken. Thanks, I'll make sure Turbolinks is properly installed in my local application and get back to you.

**Comment by bryanvero** [comment]
I have installed Turbolinks in my app and confirmed the JS is loaded, but it still hangs in my simulator. I am using http://localhost:3000, and have added the SSL cert to my keychain, and confirmed it loads properly in Safari in the simulator.

When I load my app, the webview just spins. How can I debug what is going on?

**Comment by ericgross** [comment]
It eventually started working, just had to fiddle for a while.

**Comment by sstephenson** [comment]
@bryanvero Things to double-check:

1. Make sure you’re using Turbolinks 5. Older versions won’t work.
2. You won’t need an SSL certificate to access http://localhost:3000, but you _will_ need to configure App Transport Security to allow access to unencrypted HTTP. See the [Quick Start Guide](https://github.com/turbolinks/turbolinks-ios/blob/master/QuickStartGuide.md#2-configure-your-project-for-turbolinks) for instructions.

**Comment by jonaldomo** [comment]
FWIW: I started a brand new rails project and brand new IOS project to check out the functionality.  I ran into the spinner on a brand new rails app with the URL pointing to localhost:3000.  The default index page "Yay you are rails" does not have turbolinks included.  After I pointed / to something else like /posts, it worked.
