### ISSUE TITLE
relative URLs treated like external

### ISSUE THREAD

**Issue by DCarper** [turbolinks/turbolinks-ios#55]
Relative URLs open in native Safari unless you implement

`func session(session: Session, openExternalURL URL: NSURL) {
visit(URL)
}`

Consequently, real external URL clicks do not seem to hit this method.

**Comment by zachwaugh** [comment]
Can you give me some more information? I tested in the Turbolinks demo app, and I'm unable to reproduce using a relative URL in a link, I'm seeing it hit the `session(didProposeVisitToURL:withAction:)` method and do a normal visit.
