### ISSUE TITLE
custom WKNavigationDelegate doesn't work

### ISSUE THREAD

**Issue by jun1st** [turbolinks/turbolinks-ios#56]
I'd like get some data from response headers, I think it's inside WKNavigation object. But my custom delegate not get called.

I've set my view controller as the delegate

```
func sessionDidLoadWebView(session: Session) {
        session.webView.navigationDelegate = self
}
```

here is the summary of my delegate

```
func webView(webView: WKWebView, decidePolicyForNavigationAction navigationAction: WKNavigationAction, decisionHandler: (WKNavigationActionPolicy) -> Void) {
    if let _ = navigationAction.request.URL?.absoluteString.rangeOfString("itunes.apple.com") {
        UIApplication.sharedApplication().openURL(navigationAction.request.URL!)
        decisionHandler(WKNavigationActionPolicy.Cancel)
        return
    }
    decisionHandler(WKNavigationActionPolicy.Allow)
}

func webView(webView: WKWebView, didCommitNavigation navigation: WKNavigation!) {
    print("loading...")
}

func webView(webView: WKWebView, didFinishNavigation navigation: WKNavigation!) {
    print("cool...")
}
```

the `decidePolicyForNavigationAction` method did get called, but not the other two, 

Did I miss anything?

**Comment by zachwaugh** [comment]
The `webView:didCommitNavigation` and `webView:didFinishNavigation` would only get called on the initial "cold boot" request, which by the time `sessionDidLoadWebView` is called, would have already completed. All other requests are handled by Turbolinks in JavaScript using xhr, so they don't hit the `WKNavigationDelegate` load methods.

Your best bet is to add a JavaScript event handler to listen to `turbolinks:request-end` to access the response headers - https://github.com/turbolinks/turbolinks#full-list-of-events.

**Comment by hhgz9527** [comment]
Hi, @zachwaugh 

Add JavaScript event handler to listen to `turbolinks:request-end` like this?
```swift
webView.evaluateJavaScript("document.addEventListener(\"turbolinks:request-end\", function(){ };", completionHandler: { (result, error) in

        })
```

but how to notification native app?

Thanks.
