### ISSUE TITLE
Turbolinks Demo - Build failed

### ISSUE THREAD

**Issue by ezbreaks** [turbolinks/turbolinks-ios#58]
I'm getting  some kinds of errors when I'm trying to run/build the Turbolinks Demo app.
If someone can help me I would appreciate very much.

![screen shot 2016-08-29 at 09 34 38](https://cloud.githubusercontent.com/assets/11207292/18042748/dc32b740-6dcb-11e6-9e70-339aef8e6fa2.png)

Best
Andrew

**Comment by jnstq** [comment]
I just had the same problem, upgrade to Xcode 7.3.1 and it works.

**Comment by ezbreaks** [comment]
Thanks a lot @jnstq
I thought that this should be the issue but I'm on Yosemite so I need to upgrade to El Capitan first.

Cheers

**Comment by jnstq** [comment]
Same we just updated the El Capitan :)
