### ISSUE TITLE
Using turbolinks-ios in objective-c

### ISSUE THREAD

**Issue by hgani** [turbolinks/turbolinks-ios#59]
Hi,

Has anyone managed to use turbolink-ios in their objective-c project?

Or if anyone has at least attempted to do this, could you please share your finding? 

I couldn't figure out how to invoke `session.visit(visitable)` in my objective-c project.

Thanks

**Comment by zachwaugh** [comment]
Sorry for leaving this sit. We're not currently using Objective-C anymore, so haven't tested or added any specific Obj-C support to the framework. If someone needs it, we'd be happy to look at a PR for it.
