### ISSUE TITLE
Initializer for conditional binding must have Optional type, not 'UIView'

### ISSUE THREAD

**Issue by Neilos** [turbolinks/turbolinks-ios#63]
When using Xcode 7.3.1, the following build error occurs.

```swift
VisitableView.swift:128:70: Initializer for conditional binding must have Optional type, not 'UIView'
```

<img width="787" alt="screen shot 2016-09-12 at 16 14 27" src="https://cloud.githubusercontent.com/assets/977566/18441527/4854eb7a-7905-11e6-891d-fcf1153e4c39.png">

**Comment by zachwaugh** [comment]
We're targeting Xcode 8/Swift 2.3/iOS 10 now for Turbolinks iOS, and as of iOS 10, that method has changed to return an optional UIView - https://developer.apple.com/reference/uikit/uiview/1622531-snapshotviewafterscreenupdates. If you compile with Xcode 8, there will be no warning.

**Comment by Neilos** [comment]
Cheers that worked.
