### ISSUE TITLE
"Undefined symbols for architecture x86_64" when migrating to swift 3

### ISSUE THREAD

**Issue by fiedl** [turbolinks/turbolinks-ios#64]
I've just tried a migration to swift 3 (using XCode's assistant and, after specifying the `swift-3.0` branch in the `Cartfile`, running `carthage update`).

When compiling the project, I now get:

```
Undefined symbols for architecture x86_64:
  "direct field offset for Turbolinks.VisitableViewController.(visitableView.storage in _DF3372EDB6DA8B9C7F2112D8D315974E) : Turbolinks.VisitableView!?", referenced from:
      Turbolinks.VisitableViewController.visitableView.setter : Turbolinks.VisitableView! in VisitableViewController.o
      Turbolinks.VisitableViewController.(visitableView.materializeForSet : Turbolinks.VisitableView!).(closure #1) in VisitableViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Has anyone seen something similar?

**Comment by ChennyBaBy** [comment]
I'm getting the same thing~!

**Comment by ChennyBaBy** [comment]
Hey just an update on this. I manage to fix it by rebuilding the turbolinks framework and re-linking it to the app that seemed to have made the error gone away. And I can see there was a change on the  `Modules/Turbolinks.swiftmodule/x86_64.swiftmodule` after the rebuilding the framework myself.
✨~ Good Luck ~✨

**Comment by zachwaugh** [comment]
We're using the `swift-3.0` branch with our Swift 3 app installed via Carthage without issue, so most likely a local problem. If you're still getting this, make sure to do a clean build of your project, as well as deleting derived data for both your project and Turbolinks. Looks like it's using some cached data from an older build.

**Comment by fiedl** [comment]
@ChennyBaBy @zachwaugh, thanks for your replies. Unfortunately, I'm still having this issue for Swift 3. Could you give me some pointers which cache files to remove or how to do a "clean build"?

I've just cloned my project into a separate directory, did `carthage update` and dragged `Carthage/Build/iOS/Turbolinks.framework` into XCode's "Embedded Binaries" and "Linked Frameworks and Libraries" boxes. But I still see the same "ld: symbol(s) not found for architecture x86_64".

**Comment by zachwaugh** [comment]
I just noticed above that your project was open-source, so I tested myself and was able to replicate the issue, so not related to cached data. Did some searching, and found the issue was related to subclassing a class that uses public lazy vars when used from carthage.

I just pushed a fix. Try running `carthage update` again and let me know if it works now.

**Comment by fiedl** [comment]
Thank you very much, @zachwaugh, it worked!! 😄

**Comment by zachwaugh** [comment]
Great! Thanks for confirming the fix.
