### ISSUE TITLE
Error Running Turbolinks iOS Demo

### ISSUE THREAD

**Issue by Mardiniii** [turbolinks/turbolinks-ios#71]
Hi Everybody!

I saw the talk from @sstephenson about Turbolinks 5. Now, I want to try some exercises before implementing this feature in my work. I want to be clear that I never have used X-Code, I clone this repository https://github.com/turbolinks/turbolinks-ios/ and I was trying to run the demo. I started the server with the Turbolinks 5 app but when I want to run the simulator X-Code is raising the next error and I don't know how to fix it. You can see the error on the next screenshot:

![image](https://cloud.githubusercontent.com/assets/8250324/18838854/7d9c99c6-83ce-11e6-83f3-d27b21cfb91e.png)

 Can you help me please?

**Comment by jun1st** [comment]
It's a swift 3 error when running codes in swift 2 format.

try out the swift-3.0 branch

**Comment by ChennyBaBy** [comment]
is it possible to install the `swift-3.0` branch with cocoapods? I've tried passing the branch param on the podfile like:
```ruby
pod 'Turbolinks', :git => 'https://github.com/turbolinks/turbolinks-ios.git', :branch => 'swift-3.0'
```
but they still come in at swift 2 syntax when they get put into the app.

**Comment by jun1st** [comment]
Yes, I'm using the swift-3.0 branch.
And your pod file seems good to me, maybe try `pod update`?

**Comment by chrise86** [comment]
I'm still having this issue - it does not seem to be any different using that branch. I have tried Pod update with no luck. @Mardiniii did you manage to solve this?

**Comment by zachwaugh** [comment]
I can't reproduce this with the `master` branch or `swift-3.0` branch and Xcode 8.1. Anyone seeing this issue, can you confirm you're running Xcode 8 (or 8.1) and building against the iOS 10 SDK? That was related to change with the iOS 10 SDK that made the `snapshotViewAfterScreenUpdates` method return an optional.
