### ISSUE TITLE
MobileAssetError:29 Unable to copy asset information...

### ISSUE THREAD

**Issue by joelmoss** [turbolinks/turbolinks-ios#73]
Running the demo with absolutely no changes, on latest xcode, and each time I focus on a form input (the password field in the demo), the keyboard fails to show and I get this error in the log...

```
2016-10-05 18:37:56.424457 TurbolinksDemo[25583:1766486] 0x61800014a3a0 Copy matching assets reply: XPC_TYPE_DICTIONARY  <dictionary: 0x61800014a3a0> { count = 1, transaction: 0, voucher = 0x0, contents =
    "Result" => <int64: 0x610000230100>: 29
}
2016-10-05 18:37:56.425750 TurbolinksDemo[25583:1766486] 0x618000149320 Daemon configuration query reply: XPC_TYPE_DICTIONARY  <dictionary: 0x618000149320> { count = 2, transaction: 0, voucher = 0x0, contents =
    "Dictionary" => <dictionary: 0x61800014a710> { count = 1, transaction: 0, voucher = 0x0, contents =
        "ServerURL" => <dictionary: 0x61800014a5b0> { count = 3, transaction: 0, voucher = 0x0, contents =
            "com.apple.CFURL.magic" => <uuid: 0x61800005f440> C3853DCC-9776-4114-B6C1-FD9F51944A6D
            "com.apple.CFURL.string" => <string: 0x6180002513d0> { length = 30, contents = "https://mesu.apple.com/assets/" }
            "com.apple.CFURL.base" => <null: 0x10d224f20>: null-object
        }
    }
    "Result" => <int64: 0x61800022b580>: 0
}
2016-10-05 18:37:56.426218 TurbolinksDemo[25583:1766486] [MobileAssetError:29] Unable to copy asset information from https://mesu.apple.com/assets/ for asset type com.apple.MobileAsset.TextInput.SpellChecker
```

I get the same error on a fresh Turbolinks based iOS project too using swift 2.3 and 3.

Any ideas?

**Comment by derickdorner** [comment]
I'm having the problem.. any luck? Problem occurred when syncing my desktops on OSX between work imac and home mac air, and mac air was .1 version outdated when I opened the project.

**Comment by zachwaugh** [comment]
Those are  system logs unrelated to Turbolinks. Xcode 8 turned on a bunch of noisy logs for some reason. Xcode 8.1 improved that, but still shows some logs. You can disable that following these directions - http://stackoverflow.com/a/39461256/147307.

If the keyboard isn't showing, you might have the simulator option enabled that acts as if a hardware keyboard is connected (command+shift+k to toggle). Even with the hardware keyboard enabled, you should still a bar at the bottom of the screen that allows switching between form fields. Can you confirm if that's the case? There's nothing in Turbolinks that should affect how input fields interact with the system keyboard. I see the error logs, but I can't reproduce the keyboard not showing locally with Xcode 8.1
