### ISSUE TITLE
Form submit causes view to advance.

### ISSUE THREAD

**Issue by lucadegasperi** [turbolinks/turbolinks-ios#76]
Hello, I'm fairly new to Turbolinks but i've managed to create a simple application that logs a user in and shows a reserved area. It works fine on the web. I'm now trying to run the app with Turbolinks-iOS and whenever the login form validation fails, a new VisitableViewController is pushed onto the navigation stack because after a failed login attempt i redirect via turbolinks the user to the form with the validation errors on it. I've tried using the "replace" action instead of the "advance" but still a new VisitableViewController is pushed to the navigation stack.

Any ideas on how I could solve this? I don't want to push a new VisitableViewController onto the stack unless the action is set to "advance"

**Comment by samoli** [comment]
I had a similar problem. The  demo app suggests the following:

```swift
// ApplicationController.swift
private func presentVisitableForSession(session: Session, URL: NSURL, action: Action = .Advance) {
  let visitable = DemoViewController(URL: URL)

  if action == .Advance {
    pushViewController(visitable, animated: true)
  } else if action == .Replace {
    popViewControllerAnimated(false)
    pushViewController(visitable, animated: false)   }
        
   session.visit(visitable)
}
```

But it would seem `popViewControllerAnimated` does nothing if there is only a single controller on the navigation stack.

Something like this fixed it for me:

```swift
func presentVisitableForSession(session: Session, URL: NSURL, action: Action = .Advance) {
  let visitable = VisitableViewController(URL: URL)

  if action == .Advance {
    pushViewController(visitable, animated: true)
  } else if action == .Replace {
    if viewControllers.count == 1 {
      visitable.title = title
      setViewControllers([visitable], animated: false)
    } else {
      popViewControllerAnimated(false)
      pushViewController(visitable, animated: false)
    }
  }

  session.visit(visitable)
}
```

**Comment by zachwaugh** [comment]
@samoli is correct, you'll need to handle a `replace` action. You can also just always use `setViewControllers` instead of the pop and then push, something like this (untested, but you get the idea):

```swift
let viewControllers: [UIViewController] = navigationController.viewControllers[0..<navigationController.viewControllers.count - 1] + [visitable]
navigationController.setViewControllers(viewControllers, animated: false)
```
