### ISSUE TITLE
Cannot Build Turbolinks on Xcode 8.1

### ISSUE THREAD

**Issue by joemasilotti** [turbolinks/turbolinks-ios#80]
Xcode 8.1 throws the following error when trying to build Turbolinks via CocoaPods installation:

```
#{SRC_ROOT}/Pods/Turbolinks/Turbolinks/ScriptMessage.swift:1:8: Module file was created by an older version of the compiler; rebuild 'WebKit' and try again:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos/arm64/WebKit.swiftmodule
```

This can be reproduced by opening the `swift-3.0` branch and trying to build the Turbolinks framework in Xcode 8.1.

**Comment by zachwaugh** [comment]
@joemasilotti I can't reproduce that from directly building the `swift-3.0` branch or via Carthage. Can you try doing a clean build and/or deleting derived data? Sounds like a cache issue from an older version.

**Comment by joemasilotti** [comment]
I'm still not entirely sure why this occurred, but deleting the following file resolved my issue. Closing.

`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator/x86_64/WebKit.swiftmodule`

**Comment by zachwaugh** [comment]
Cool, thanks for the confirming!
