### ISSUE TITLE
Support 3D Touch

### ISSUE THREAD

**Issue by adamdebono** [turbolinks/turbolinks-ios#84]
WKWebView now supports 3d touch functionality by adding methods to WKUIDelegate. The web view that you are pressing on needs to remain in view for this to work, moving it to another view controller during the press halts the application's UI (I doubt that UIKit is expecting this). A secondary WKWebView may need to be created to support this.

The default functionality for WKWebView, which is how turbolinks currently behaves, is to show an SFSafariViewController for a "peek", and will open the link in safari on pop.

**Comment by zachwaugh** [comment]
3d touch doesn't really work well with Turbolinks' architecture of using a single webview. We'd have to use a separate webview for the peek, which would then have to do a full cold boot visit, negating the Turbolinks performance gains. Apps can still implement it directly by implementing `WKNavigationDelegate` methods, but I don't think we'll build in support to the framework for it.
