### ISSUE TITLE
Turbolinks fails to builds when using cocoapods in Xcode 8.1

### ISSUE THREAD

**Issue by mityakoval** [turbolinks/turbolinks-ios#85]
I'm trying to build my test project with Turbolinks module using cocoapods. However, it raises 105 errors when I'm doing that. 
![screen shot 2016-12-07 at 18 03 53](https://cloud.githubusercontent.com/assets/10942685/20978027/a6647740-bca7-11e6-936e-87c4a7e20702.png)
![screen shot 2016-12-07 at 18 04 11](https://cloud.githubusercontent.com/assets/10942685/20978028/a689141a-bca7-11e6-9516-9bc96e50a706.png)

**Comment by zachwaugh** [comment]
Looks like a mismatch between Swift versions. What version of Swift are you using in your project? Turbolinks currently supports Swift 2.3, and there is a Swift 3.0 branch as well `swift-3.0`.

**Comment by mityakoval** [comment]
Yeah, I kind of suspected it but managed to fix it just now :) Changed the build settings 'Use Legacy Swift Language Version' => 'Yes'. Everything seems to be building and I can import Turbolinks module now. 
Closing the issue.

Just a brief question: when are you going to merge `swift-3.0` branch with `master`

**Comment by zachwaugh** [comment]
@mityakoval we'll be merging swift-3.0 into master soon, currently testing it in internal builds now to make sure there are no regressions, but it's stable.

**Comment by MrHubble** [comment]
@mityakoval did you change the build settings 'Use Legacy Swift Language Version' => 'Yes' under your project settings or is it something to do with Turbolinks directly? I've changed it myself for my project but Turbolinks still has build errors.

![screen shot 2017-02-20 at 4 10 37 pm](https://cloud.githubusercontent.com/assets/2251631/23112783/323d9a20-f787-11e6-8a49-fa1ada20bb5e.png)

**Comment by MrHubble** [comment]
Update: I have it working now but am unsure which of the below steps fixed it:

- updated Sierra to 10.12.3 (I was on an older version of Sierra)
- updated xcode to 8.2.1 (I was previously on 8.1.x)
- created a new project and changed _Use Legacy Swift Language Version_ to **Yes** before adding Turbolinks with cocoapods

**Comment by mityakoval** [comment]
@MrHubble Well, my not really educated guess would be the latter two :)
