### ISSUE TITLE
WebView is black when the app is launched

### ISSUE THREAD

**Issue by mityakoval** [turbolinks/turbolinks-ios#87]
I decided to split the app in two controllers (before that everything was written in `AppDelegate.swift`) to separate authentication flow from the main one. I followed `TurbolinksDemo` in this repo.

The first question is how does your app work in that demo with this:
```
func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        return true
    }
```
How does it invoke ApplicationController?

Anyway, I assigned `ApplicationController` to the `rootViewController` and it resulted in a black screen with blank navigation bar. 

I can see that it actually hits the server and RoR renders the view which never gets displayed. 

I'm not an iOS developer so I apologise in advance if I did something very stupid.

Here is the repo with the project: [vaktboka-ios](https://github.com/mityakoval/vaktboka-ios)

![img_0753](https://cloud.githubusercontent.com/assets/10942685/22084927/52ab6d24-ddd2-11e6-92df-beb38ee7bb6e.PNG)

**Comment by thetizzo** [comment]
For me, I have the Application Controller marked as the Initial View Controller in Main.storyboard.  I'm also new to iOS stuff but I believe this sets it up so that the AppDelegate knows that this controller is the first one to load and will execute it's viewDidLoad method when the app loads.

You can find this check box in the Attributes inspector pane when you open Main.storyboard.

<img width="1655" alt="main_storyboard" src="https://cloud.githubusercontent.com/assets/709926/22085619/06cc6d80-dd92-11e6-8f08-837fa5e6f8d4.png">

**Comment by mityakoval** [comment]
Thank you, @thetizzo 
I suspected something like this :)
I did as you suggested and set an initial viewController properly but, unfortunately, it didn't fix the problem with the black screen.

**Comment by zachwaugh** [comment]
If you're using storyboards, you'll need to set the custom class for the view controller within Interface Builder to be `ApplicationController` (or whatever controller you want). Looks like you were setting the `rootViewController` from code, then the storyboard was overwriting it with a blank view controller when it is loaded.

![image](https://cloud.githubusercontent.com/assets/21447/22124690/dd5b218a-de5e-11e6-9457-b716ca4ece5e.png)

**Comment by thetizzo** [comment]
@mityakoval I pulled your project and noticed that in your MainViewController's viewDidLoad method you aren't calling super.viewDidLoad().  Once I added that I ran the project and a log in screen came right up.

**Comment by mityakoval** [comment]
Thank you @thetizzo and @zachwaugh for your time. That was stupid :)
One brief question: when is `authenticationControllerDidAuthenticate()` method fired?
