### ISSUE TITLE
Javascript  `confirm` modal not opening

### ISSUE THREAD

**Issue by benjamreynolds** [turbolinks/turbolinks-ios#88]
It appears as though Javascript `confirm` modals do not open inside a turbolinks based iOS apps. `alert` modals work fine and use the native `alert` modal found in safari. Is there a way around this without making custom confirm modals?

**Comment by kdeggelman** [comment]
Same issue here...

Something like `<%= link_to "Test Button", root_path, data: { confirm: "Are you sure you want to go there?"} %>` does not work in turbolinks ios

**Comment by zachwaugh** [comment]
That's a `WKWebView` issue, you need to implement a `WKUIDelegate`, specifically this method:

```swift
optional func webView(_ webView: WKWebView, runJavaScriptConfirmPanelWithMessage message: String, initiatedByFrame frame: WKFrameInfo, completionHandler: @escaping (Bool) -> Void)
```

https://developer.apple.com/reference/webkit/wkuidelegate/1536489-webview

**Comment by dpaola2** [comment]
Anyone have an example of this implemented in a Turbolinks app they'd be willing to share?

**Comment by zachwaugh** [comment]
Simplest is just to use a `UIAlertController`, this should work:

```swift
func webView(_ webView: WKWebView, runJavaScriptConfirmPanelWithMessage message: String, initiatedByFrame frame: WKFrameInfo, completionHandler: @escaping (Bool) -> Void) {
    let alert = UIAlertController(title: nil, message: message, preferredStyle: .alert)
    alert.addAction(UIAlertAction(title: "OK", style: .default, handler: { _ in
        completionHandler(true)
    }))
    
    alert.addAction(UIAlertAction(title: "Cancel", style: .cancel, handler: { _ in
        completionHandler(false)
    }))
    
    // If your WKUIDelegate is a view controller, can just call this on self
    viewController.present(alert, animated: true, completion: nil)
}
```

**Comment by dpaola2** [comment]
Awesome thank you very much!

**Comment by Pepan** [comment]
It is still not solved :( when you use `data-confirm` and do back and fort with browser navigation, clicking on link with `data-confirm` just flashes and does nothing.
