### ISSUE TITLE
Cookie sharing

### ISSUE THREAD

**Issue by mityakoval** [turbolinks/turbolinks-ios#89]
It has been mentioned that Turbolinks 5 stores tokens and session cookies that are automatically persisted:
 https://github.com/turbolinks/turbolinks-ios/issues/30#issuecomment-210072877 https://github.com/turbolinks/turbolinks-ios/issues/39#issuecomment-237669770

So I need to post some data back to my Rails app on successful login which I am doing in `authenticationControllerDidAuthenticate()` via `NSURLSession`

However, neither cookies nor tokens are not sent along with the request. `NSHTTPCookieStorage.sharedCookieStorage().cookies` is empty so I cannot retrieve them manually.

I am sharing `webViewConfiguration` across views and using a single `WKProcessPool`

Is this an issue with my code or with Turbolinks?

**Comment by zachwaugh** [comment]
You can't directly access the cookies in a `WKWebView`, as they're not stored in the `NSHTTTPCookieStorage.sharedCookieStorage`, like it is with `UIWebView`. The web view itself will persist them and send them correctly with each request made within the web view, or other web views in the same process pool. So you can tell the web view to make a XHR request, or you'll have to use another method for authenticating NSURLSession requests. We use OAuth tokens for the native requests, and there are some options for doing that in this issue #39

**Comment by lucadegasperi** [comment]
@zachwaugh we'd love to see how you handle authentication between the web view and the native part!
