### ISSUE TITLE
Possible to use without Rails?

### ISSUE THREAD

**Issue by RobertCordes** [turbolinks/turbolinks-ios#90]
Probably a stupid question but I wanted to be sure. Is it possible to use this without a Rails app? I normally build Rails apps but we have to create our next one with Laravel and there has to be an iOS/Android version.

Have a nice day!

**Comment by exalted** [comment]
@RobertCordes AFAIK absolutely! In fact, the [demo app](https://github.com/turbolinks/turbolinks-ios/tree/master/TurbolinksDemo) is a tiny sinatra app (check out the [`Gemfile`](https://github.com/turbolinks/turbolinks-ios/blob/caa6d949afbd19f597ea5c6b938e094cc9dbd517/TurbolinksDemo/server/Gemfile#L3)).

As per the README:

> Turbolinks for iOS provides the tooling to wrap your **Turbolinks 5-enabled web app** in a native iOS shell [emphasis mine].

Cheers! 🍻

**Comment by exalted** [comment]
> Laravel

I probably should also point out that, I am not sure whether Laravel does/can support [Turbolinks](https://github.com/turbolinks/turbolinks) or not, but Rails is **not** a strict dependency.

**Comment by RobertCordes** [comment]
@exalted Great, thanks! That’s good to know. When I have the time I will do a quick test and post my findings here ;-) Just in case anyone else wants to know.

**Comment by exalted** [comment]
That would be great @RobertCordes. Have a nice day!

**Comment by emilsundberg** [comment]
@RobertCordes Did you get things working with Laravel and Turbolinks? I'm trying it out right now but no success yet.

**Comment by RobertCordes** [comment]
@emilsundberg Yeah, I basically got it working though didn't get it to play nice with Vue. I still have it somewhere so if you have any specific questions maybe I can help. (I don't really remember what I did step by step).

**Comment by emilsundberg** [comment]
@RobertCordes If you want to share I'd love to see your solution. Contact details in profile.

I got our first attempt working with the Laravel backend now :)
