### ISSUE TITLE
Demo project setup: bundle install fails

### ISSUE THREAD

**Issue by dacur** [turbolinks/turbolinks-ios#96]
I followed the instructions for setting up the demo project; however, when running `TurbolinksDemo/demo-server`, the bundle install would fail.

I changed line 19 of the demo-server file from `gem contents bundler | grep "/exe/bundle$" | head -n 1` to `gem contents bundler | grep "/bin/bundle$" | head -n 1` and was able to start the server and run the demo without incident.

**Comment by packagethief** [comment]
It may be due to your Ruby and/or Bundler versions. What versions are you running?

```
ruby --version
gem --version
bundle --version
```

**Comment by dacur** [comment]
Thanks for the quick response @packagethief !  I didn't see an issue that had been opened in the past regarding this issue, so I wanted to open it for anyone else that might have it in the future and note the fix that I used to resolve it.

`ruby 2.2.3p173`
`2.6.10`
`Bundler version 1.14.6`

**Comment by zachwaugh** [comment]
Haven't been able to replicate, so assuming it was a local issue.

**Comment by dkam** [comment]
Looks like it doesn't currently work. The Gemfile.lock requires bundler version 1

```
$ ./demo-server
Starting the demo server (press ^C to exit)...
Installing Bundler...
Installing dependencies...
Error running `bundle install`
```

Installed 
```
$ ruby --version
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin19]
$ gem --version
3.1.2
$ bundle --version
Bundler version 2.1.4
```

I updated the Gemfile to work with Bundler 2.1.4 and updated the Gemfile.lock and the server booted up ok.
[Gemfile.lock.txt](https://github.com/turbolinks/turbolinks-ios/files/4556372/Gemfile.lock.txt)
