### ISSUE TITLE
Download and save image / pdf

### ISSUE THREAD

**Issue by Solidhan5000** [turbolinks/turbolinks-ios#99]
Hello all,

My turbolinks 5 enables web app works very well in turbolink-ios. Very happy with that. However, I am not able to download images or files via an anchor. In my web-app the images & files download just fine when the anchor is:

`<a target="_blank" href="SOME JPG OR PDF">Download</a>`

I my iOS app, the app just opens Safari and the image or file is not downloading saving to the phone.

I guess the first step would be to intercept this specific request and call some form of downloader class. However I cannot seem to intercept the visit.  I have tried:

```
func session(_ session: Session, didProposeVisitToURL URL: Foundation.URL, withAction action: Action) {
        if URL.absoluteString.contains(".jpg") {
            // go to some downloader class.
        } else {
            presentVisitableForSession(session, url: URL, action: action)
        }
    }
```
So it is actually two questions:
1. How do I intercept the visit?
2. Any idea on to implement a downloader class.

**Comment by zachwaugh** [comment]
Turbolinks will requests for files and won't propose a visit to them. You should implement the `WKNavigationDelegate` methods and handle all the non-Turbolinks link clicks there. For Basecamp, we send all those URLs through a `Router` class which decides how to handle them. It may open external links in Safari, open a media viewer/downloader for things like PDFs or JPGs, or handle it in some other way depending on the URL.
